services:
  # Servicio del Frontend (React)
  frontend:
    build:
      context: ./excursiones # Ahora la ruta es relativa a la nueva ubicación del yml
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Mapea el puerto 3000 de tu máquina al 80 del contenedor
    depends_on:
      - backend
  # Servicio del Backend (Node.js/Express)
  backend:
    build:
      context: ./testserver # Corregimos la ruta para que no use '..'
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Mapea el puerto 3001 de tu máquina al 3001 del contenedor
    env_file: ./testserver/.env
    environment:
      - NODE_ENV=development
    stdin_open: true # Mantiene el contenedor en ejecución
    tty: true # Asigna un pseudo-TTY
